#!/bin/zsh
# Shell UPdate
# This script updates all the tools used in the shell

# Load colors
autoload colors; colors

# be sure to source the zshrc file to have access to omz, $ZSH_CUSTOM
source ~/.zshrc

# ZSH TOOLS UPDATE ------------------------------------------------------------
# Oh-my-zsh update
# echo $fg[green]"Updating Oh-my-zsh..."$reset_color # No need to print as it's already done in omz update
omz update --unattended
echo ""

# Powerlevel10k update
if [ -d "$ZSH_CUSTOM/themes/powerlevel10k" ]; then
    echo $fg[green]"Updating Powerlevel10k..."$reset_color
    cd "$ZSH_CUSTOM/themes/powerlevel10k"
    git pull
    echo ""
fi

# Spaceship update
if [ -d "$ZSH_CUSTOM/themes/spaceship-prompt" ]; then
    echo $fg[green]"Updating Spaceship..."$reset_color
    cd "$ZSH_CUSTOM/themes/spaceship-prompt"
    git pull
    echo ""
fi

# Zsh-autosuggestions update
if [ -d "$ZSH_CUSTOM/plugins/zsh-autosuggestions" ]; then
    echo $fg[green]"Updating Zsh-autosuggestions..."$reset_color
    cd "$ZSH_CUSTOM/plugins/zsh-autosuggestions"
    git pull
    echo ""
fi

# Zsh-completions update
if [ -d "$ZSH_CUSTOM/plugins/zsh-completions" ]; then
    echo $fg[green]"Updating Zsh-completions..."$reset_color
    cd "$ZSH_CUSTOM/plugins/zsh-completions"
    git pull
    echo ""
fi

# # Zsh-syntax-highlighting update
# if [ -d "$ZSH_CUSTOM/plugins/zsh-syntax-highlighting" ]; then
#     echo $fg[green]"Updating Zsh-syntax-highlighting..."$reset_color
#     cd "$ZSH_CUSTOM/plugins/zsh-syntax-highlighting"
#     git pull
#     echo ""
# fi

# fast-syntax-highlighting update
if [ -d "$ZSH_CUSTOM/plugins/fast-syntax-highlighting" ]; then
    echo $fg[green]"Updating fast-syntax-highlighting..."$reset_color
    cd "$ZSH_CUSTOM/plugins/fast-syntax-highlighting"
    git pull
    echo ""
fi

# -----------------------------------------------------------------------------

# CLI TOOLS UPDATE -----------------------------------------------------------

if [ "$PLATFORM"  = 'mac' ]; then
    brew update

    # Starship update
    # echo $fg[green]"Updating Starship..."$reset_color
    # brew install starship
    # echo ""

    # Update thefuck
    echo $fg[green]"Updating thefuck..."$reset_color
    brew install thefuck
    echo ""

    # Update fd
    echo $fg[green]"Updating fd..."$reset_color
    brew install fd
    echo ""

    # Update tree
    echo $fg[green]"Updating tree..."$reset_color
    brew install tree
    echo ""

    # Update bat
    echo $fg[green]"Updating bat..."$reset_color
    brew install bat
    echo ""

    # Update fzf
    echo $fg[green]"Updating fzf..."$reset_color
    brew install fzf
    echo ""

    # Update direnv
    echo $fg[green]"Updating direnv..."$reset_color
    brew install direnv
    echo ""

    # Update catimg
    echo $fg[green]"Updating catimg..."$reset_color
    brew install catimg
    echo ""

    # Update stow
    echo $fg[green]"Updating stow..."$reset_color
    brew install stow
    echo ""

    # Update colorls
    echo $fg[green]"Updating colorls..."$reset_color
    gem update colorls
    echo ""

    # Update ripgrep
    echo $fg[green]"Updating ripgrep..."$reset_color
    brew install ripgrep
    echo ""

    # Update neovim
    echo $fg[green]"Updating neovim..."$reset_color
    brew install neovim
    echo ""

    # Update duf
    echo $fg[green]"Updating duf..."$reset_color
    brew install duf
    echo ""

    # # Update lsd
    # echo $fg[green]"Updating lsd..."$reset_color
    # brew install lsd
    # echo ""

    # Update jq
    echo $fg[green]"Updating jq..."$reset_color
    brew install jq
    echo ""

    # Update yazi
    echo $fg[green]"Updating yazi..."$reset_color
    brew install yazi ffmpegthumbnailer unar poppler font-symbols-only-nerd-font
    echo ""
fi
if [ "$PLATFORM"  = 'linux' ]; then
    sudo apt-get update

    # Starship update
    # echo $fg[green]"Updating Starship..."$reset_color
    # curl -sS https://starship.rs/install.sh | sh
    # echo ""

    # Update thefuck
    echo $fg[green]"Updating thefuck..."$reset_color
    pip3 install thefuck --upgrade
    echo ""

    # Update fd
    echo $fg[green]"Updating fd..."$reset_color
    sudo apt-get --only-upgrade install fd-find -y
    echo ""

    # Update tree
    echo $fg[green]"Updating tree..."$reset_color
    sudo apt-get --only-upgrade install tree -y
    echo ""

    # Update bat
    echo $fg[green]"Updating bat..."$reset_color
    sudo apt-get --only-upgrade install bat -y
    echo ""

    # Update fzf
    echo $fg[green]"Updating fzf..."$reset_color
    sudo apt-get --only-upgrade install fzf -y
    echo ""

    # Update direnv
    echo $fg[green]"Updating direnv..."$reset_color
    sudo apt-get --only-upgrade install direnv -y
    echo ""

    # Update catimg
    echo $fg[green]"Updating catimg..."$reset_color
    sudo apt-get --only-upgrade install catimg -y
    echo ""

    # Update stow
    echo $fg[green]"Updating stow..."$reset_color
    sudo apt-get --only-upgrade install stow -y
    echo ""

    # Update colorls
    echo $fg[green]"Updating colorls..."$reset_color
    sudo gem update colorls
    echo ""

    # Update ripgrep
    echo $fg[green]"Updating ripgrep..."$reset_color
    sudo apt-get --only-upgrade install ripgrep -y
    echo ""

    # Update neovim
    echo $fg[green]"Updating neovim..."$reset_color
    sudo snap refresh nvim
    echo ""

    # Update duf
    echo $fg[green]"Updating duf..."$reset_color
    sudo apt-get --only-upgrade install duf -y
    echo ""

    # # Update lsd
    # echo $fg[green]"Updating lsd..."$reset_color
    # sudo apt-get --only-upgrade install lsd -y
    # echo ""

    # Update jq
    echo $fg[green]"Updating jq..."$reset_color
    sudo apt-get --only-upgrade install jq -y
    echo ""
fi

if [ -d "$HOME/.config/nvim" ]; then
    echo $fg[green]"Updating Nvchad..."$reset_color
    cd "$HOME/.config/nvim"
    git pull --depth=20
    echo ""
fi

# -----------------------------------------------------------------------------

# DOTFILES UPDATE -------------------------------------------------------------
# Cd to dotfiles root
echo $fg[green]"Updating dotfiles..."$reset_color
cd ~/.dotfiles
# Update dotfiles
git pull
echo ""

# Restow dotfiles
stow -R */

# -----------------------------------------------------------------------------